### ISSUE TITLE
webob 1.6.0 now returns json in exception body response

### ISSUE THREAD

**Issue by mriedem** [Pylons/webob#235] opened 2016-03-18 21:11 UTC
This is due to https://github.com/Pylons/webob/pull/230.

Noted in this OpenStack bug:

https://bugs.launchpad.net/keystoneauth/+bug/1559072

There are a bunch of clients in openstack that were getting by with handling error response bodies like this:

https://github.com/openstack/python-openstackclient/blob/2.2.0/openstackclient/common/exceptions.py#L125

https://github.com/openstack/python-cinderclient/blob/master/cinderclient/exceptions.py#L183

https://github.com/openstack/python-novaclient/blob/3.3.0/novaclient/exceptions.py#L298

The request was asking for json:

DEBUG (session:248) REQ: curl -g -i -X GET http://10.0.1.3:8774/v1.1/b77d640e127e488fb42a7c0716ba53a5 -H "User-Agent: python-novaclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}381893576ad46c62b587f4963d769b89441b919a"

And now getting back json:

DEBUG (session:277) RESP: [404] Date: Fri, 18 Mar 2016 12:41:59 GMT Connection: keep-alive Content-Type: application/json; charset=UTF-8 Content-Length: 112 X-Compute-Request-Id: req-f10a2016-9a88-48fd-af1d-5f800fc9e11a
RESP BODY: {"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}

So this client code blows up now.

As pointed out in the discussion on pull request 230, this changes returning text/html to json, which is arguably the correct thing to do, but its is a backward incompatible change for clients.

I'm only raising this issue to bring it up.  Maybe this should have been released as a major version 2.0 bump?

**Comment by mmerickel** [comment] 2016-03-18 22:42
Looking at the impl it might have been wise to prioritize text/html over application/json in the case of ambiguities for bw-compat. I find it hard to argue with the current behavior though, and now that it's released I don't find it compelling to go backward.

I've never written a client that required a particular content type (without checking) on an error status code so I consider this a bug in openstack that we've exposed (for better or worse). Openstack should also be setting the accept header if it really expected html. All that being said I understand that this is a bw-incompat change and it sucks having to fix it on a whim.

Anyway, that's my 2c.

**Comment by mriedem** [comment] 2016-03-18 23:06
I think text/html was wrong, looking at the webob code it looks like it would default to returning plain before.

FWIW, it looks like we are requesting application/json, e.g.:

DEBUG (connectionpool:387) "GET /v2.1/e4f68bae118f46fa986e3fd54cbacb1e/flavors/test HTTP/1.1" 404 77
DEBUG (session:277) RESP: [404] Content-Length: 77 X-Compute-Request-Id: req-d9df03b0-4150-4b53-8157-7560ccf39f75 Vary: X-OpenStack-Nova-API-Version Connection: keep-alive X-Openstack-Nova-Api-Version: 2.25 Date: Fri, 18 Mar 2016 22:30:46 GMT Content-Type: application/json; charset=UTF-8
RESP BODY: {"itemNotFound": {"message": "Flavor test could not be found.", "code": 404}}


The problem is that with webob<1.6.0 we got a nested dict for the response body, with webob>=1.6.0 we now get just that single dict with the message and code in it.

The client code in this case doesn't know the version of webob being used on the server, so I'm going to just have to write some handler code that checks if message is in the body or not, and if not, assume it's webob<1.6.0.  But that's going to have to be duplicate across several clients.

**Comment by mriedem** [comment] 2016-03-18 23:06
To clarify, that request/response above is with using webob 1.5.1.

**Comment by mriedem** [comment] 2016-03-18 23:27
Same test, this time with webob 1.6.0:

DEBUG (connectionpool:387) "GET /v2.1/e4f68bae118f46fa986e3fd54cbacb1e HTTP/1.1" 404 112
DEBUG (session:277) RESP: [404] Date: Fri, 18 Mar 2016 23:26:14 GMT Connection: keep-alive Content-Type: application/json; charset=UTF-8 Content-Length: 112 X-Compute-Request-Id: req-c5e534d7-a369-4b1e-83cb-1179c97409ac
RESP BODY: {"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}

**Comment by bertjwregeer** [comment] 2016-03-19 06:14
I am not sure what the OpenStack API's are doing to the exception objects in the first place, since by default if you set explanation and return a text format, the content-type would be `text/plain` not `application/json` so somewhere in the stack nova is already messing with the exception before it is sent out.

----

https://github.com/openstack/nova/blob/stable/mitaka/nova/api/openstack/wsgi.py#L1037

Is the `Fault` object that takes care of exactly that...

Here is the code that modifies the exception object:

https://github.com/openstack/nova/blob/stable/mitaka/nova/api/openstack/wsgi.py#L1060-L1092

It sets the `.content_type` and then sets `.text` which in `Response` sets `.body`:

https://github.com/Pylons/webob/blob/1.6-branch/webob/response.py#L409

In the exception's `__call__` function we should then hit the following branch, because body is set:

https://github.com/Pylons/webob/blob/1.6-branch/webob/exc.py#L356 (`.body` is set, because calling `.text` sets `.body`, so we don't need to generate a response)

This should send out the response without any further modifications, because `generate_response` is never called, and thus we don't make any further modifications to the exception response on the way out.

This flow should not have changed since 1.5...

**Comment by bertjwregeer** [comment] 2016-03-19 06:39
```
def test_WSGIHTTPException_call_w_text():
    def start_response(_status, _headers, exc_info=None):
        for header in _headers:
            if header[0] == 'content-type':
                assert_equal(header[1], 'application/json; charset=utf-8')

    environ = {
       'wsgi.url_scheme': 'HTTP',
       'SERVER_NAME': 'localhost',
       'SERVER_PORT': '80',
       'REQUEST_METHOD': 'GET'
    }

    excep = webob_exc.WSGIHTTPException(explanation="Something is amiss...")

    # Customize our exception
    excep.content_type = 'application/json'
    excep.charset = 'utf-8'
    excep.text = u'test'

    ret = excep(environ, start_response)
    assert_equal(ret, [b'test'])
```

Very simple test case that showcases how WebOb does not modify the body nor does generate_response get called in this situation.

**Comment by bertjwregeer** [comment] 2016-03-19 07:01
Here is a full diff between WebOb 1.5 and WebOb 1.6, I've linked directly to `exc.py`:

https://github.com/Pylons/webob/compare/1.5-branch...1.6-branch#diff-40782b078f9e2517b6b73f5a707cbae3

**Comment by mriedem** [comment] 2016-03-19 13:42
That analysis looks correct. I see how nova-api is creating the nested dict body for the fault here:

https://github.com/openstack/nova/blob/stable/mitaka/nova/api/openstack/wsgi.py#L1073-L1076

But somewhere between that and when the client gets the response, that is changed.

**Comment by bertjwregeer** [comment] 2016-03-19 16:28
Going over the code again, specifically the diff between 1.5 and 1.6, I don't see how the changes made in WebOb are leading to this result.

I don't know enough about nova-api to deep dive into it and understand exactly what is going on, do you or do you know someone in the nova project that could help us debug exactly what is going on?

**Comment by bertjwregeer** [comment] 2016-03-19 17:06
Running the nova tox tests:

```
(nova)Sterling:nova xistence$ tox -e py27 nova.tests.unit.api.openstack.test_faults
py27 develop-inst-noop: /Users/xistence/Projects/nova
py27 installed: alembic==0.8.4,amqp==1.4.9,anyjson==0.3.3,appdirs==1.4.0,Babel==2.2.0,bandit==0.17.3,boto==2.39.0,cachetools==1.1.5,castellan==0.4.0,cffi==1.5.2,cliff==2.0.0,cmd2==0.6.8,contextlib2==0.5.1,coverage==4.0.3,cryptography==1.2.3,debtcollector==1.3.0,decorator==4.0.9,docutils==0.12,dogpile.cache==0.5.7,dogpile.core==0.4.1,ecdsa==0.13,enum34==1.1.2,eventlet==0.18.4,extras==0.0.3,fasteners==0.14.1,fixtures==1.4.0,flake8==2.2.4,funcsigs==0.4,functools32==3.2.3.post2,futures==3.0.5,futurist==0.13.0,gitdb==0.6.4,GitPython==1.0.2,greenlet==0.4.9,hacking==0.10.2,httplib2==0.9.2,idna==2.0,ipaddress==1.0.16,iso8601==0.1.11,Jinja2==2.8,jsonpatch==1.13,jsonpointer==1.10,jsonschema==2.5.1,keystoneauth1==2.3.0,keystonemiddleware==4.3.0,kombu==3.0.34,linecache2==1.0.0,lxml==3.5.0,Mako==1.0.3,MarkupSafe==0.23,mccabe==0.2.1,mock==1.3.0,monotonic==0.6,mox3==0.14.0,msgpack-python==0.4.7,netaddr==0.7.18,netifaces==0.10.4,-e git+git@github.com:openstack/nova.git@c4763d46fe76c524363a0cf55d1e8afe4bd23f53#egg=nova,numpy==1.10.4,openstackdocstheme==1.3.0,openstacksdk==0.8.1,os-brick==1.1.0,os-client-config==1.16.0,os-testr==0.6.0,os-win==0.2.3,oslo.cache==1.5.0,oslo.concurrency==3.6.0,oslo.config==3.9.0,oslo.context==2.2.0,oslo.db==4.6.0,oslo.i18n==3.4.0,oslo.log==3.2.0,oslo.messaging==4.5.1,oslo.middleware==3.7.0,oslo.policy==1.5.0,oslo.reports==1.6.0,oslo.rootwrap==4.1.0,oslo.serialization==2.4.0,oslo.service==1.7.0,oslo.utils==3.7.0,oslo.versionedobjects==1.7.0,oslo.vmware==2.5.0,oslosphinx==4.3.0,oslotest==2.3.0,paramiko==1.16.0,Paste==2.0.2,PasteDeploy==1.5.2,pbr==1.8.1,pep8==1.5.7,pika==0.10.0,pika-pool==0.1.3,positional==1.0.1,prettytable==0.7.2,psutil==1.2.1,psycopg2==2.6.1,pyasn1==0.1.9,pycadf==2.1.0,pycparser==2.14,pycrypto==2.6.1,pyflakes==0.8.1,Pygments==2.1.3,PyMySQL==0.7.2,pyparsing==2.1.0,pyrsistent==0.11.12,python-barbicanclient==4.0.0,python-cinderclient==1.6.0,python-dateutil==2.5.0,python-editor==0.5,python-glanceclient==2.0.0,python-ironicclient==1.2.0,python-keystoneclient==2.3.1,python-mimeparse==1.5.1,python-neutronclient==4.1.1,python-novaclient==3.3.0,python-openstackclient==2.2.0,python-subunit==1.2.0,pytz==2015.7,PyYAML==3.11,reno==1.6.1,repoze.lru==0.6,requests==2.9.1,requests-mock==0.7.0,requestsexceptions==1.1.3,retrying==1.3.3,rfc3986==0.3.1,Routes==2.2,simplejson==3.8.2,six==1.10.0,smmap==0.9.0,Sphinx==1.2.3,SQLAlchemy==1.0.12,sqlalchemy-migrate==0.10.0,sqlparse==0.1.18,stevedore==1.12.0,suds-jurko==0.6,tempest-lib==1.0.0,Tempita==0.5.2,testrepository==0.0.20,testresources==1.0.0,testscenarios==0.5.0,testtools==2.0.0,traceback2==1.4.0,unicodecsv==0.14.1,unittest2==1.1.0,urllib3==1.14,warlock==1.2.0,WebOb==1.6.0,websockify==0.8.0,wrapt==1.10.6
py27 runtests: PYTHONHASHSEED='969904699'
py27 runtests: commands[0] | find . -type f -name *.pyc -delete
py27 runtests: commands[1] | bash tools/pretty_tox.sh nova.tests.unit.api.openstack.test_faults
running testr
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-160} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./nova/tests} --list 
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-160} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./nova/tests}  --load-list /var/folders/tk/ytdq2d853qg876wgkv01v7cm0000z9/T/tmpgH3oX_
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-160} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./nova/tests}  --load-list /var/folders/tk/ytdq2d853qg876wgkv01v7cm0000z9/T/tmpK_bolB
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-160} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./nova/tests}  --load-list /var/folders/tk/ytdq2d853qg876wgkv01v7cm0000z9/T/tmp6GqZZK
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-160} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./nova/tests}  --load-list /var/folders/tk/ytdq2d853qg876wgkv01v7cm0000z9/T/tmp_Dd0WN
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-160} \
${PYTHON:-python} -m subunit.run discover -t ./ ${OS_TEST_PATH:-./nova/tests}  --load-list /var/folders/tk/ytdq2d853qg876wgkv01v7cm0000z9/T/tmps03Q9b
{0} nova.tests.unit.api.openstack.test_faults.TestFaults.test_400_fault_json [0.253769s] ... ok
{3} nova.tests.unit.api.openstack.test_faults.TestFaultWrapper.test_safe_exception_translated [0.119332s] ... ok
{4} nova.tests.unit.api.openstack.test_faults.TestFaults.test_413_fault_json [0.059437s] ... ok
{2} nova.tests.unit.api.openstack.test_faults.TestFaults.test_fault_has_status_int [0.069067s] ... ok
{1} nova.tests.unit.api.openstack.test_faults.TestFaults.test_429_fault_json [0.056958s] ... ok
Slowest Tests
Test id                                                                                    Runtime (s)
-----------------------------------------------------------------------------------------  -----------
nova.tests.unit.api.openstack.test_faults.TestFaults.test_400_fault_json                   0.254
nova.tests.unit.api.openstack.test_faults.TestFaultWrapper.test_safe_exception_translated  0.119
nova.tests.unit.api.openstack.test_faults.TestFaults.test_fault_has_status_int             0.069
nova.tests.unit.api.openstack.test_faults.TestFaults.test_413_fault_json                   0.059
nova.tests.unit.api.openstack.test_faults.TestFaults.test_429_fault_json                   0.057

======
Totals
======
Ran: 5 tests in 21.0000 sec.
 - Passed: 5
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 0.5586 sec.

==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:00:00.253769
 - Worker 1 (1 tests) => 0:00:00.056958
 - Worker 2 (1 tests) => 0:00:00.069067
 - Worker 3 (1 tests) => 0:00:00.119332
 - Worker 4 (1 tests) => 0:00:00.059437
_________________________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________________________
  py27: commands succeeded
  congratulations :)
```

With WebOb 1.6.0 (see output above on versions installed), passes the tests for `Fault` with flying colours.

The tests are defined here: https://github.com/openstack/nova/blob/master/nova/tests/unit/api/openstack/test_faults.py#L72

**Comment by bertjwregeer** [comment] 2016-03-19 17:54
Running full testing on nova, results in no failures with WebOb 1.6.0.

**Comment by mriedem** [comment] 2016-03-19 22:12
The py27 unit tests wouldn't show this with nova. I ran the functional tests which actually run a wsgi stack with webob 1.6.0 and those didn't fail either. So we might be dealing with something in the client stack (maybe keystoneauth1?).

**Comment by bertjwregeer** [comment] 2016-03-20 02:25
@mriedem The JSON you are getting back is the JSON that WebOb generates, but I don't see where in Nova's stack it is being generated.

**Comment by soulxu** [comment] 2016-03-22 09:47
@bertjwregeer @mriedem For the resource didn't register to the route_mapper, it return fault directly at https://github.com/openstack/nova/blob/stable/mitaka/nova/wsgi.py#L460

**Comment by bertjwregeer** [comment] 2016-03-22 14:23
@soulxu In the case of the errors above, that would have NEVER returned a custom JSON exception, under WebOb 1.5 or 1.6. WebOb 1.6 arguably does the better thing and tries to change the response to match what the client requested.

What we are trying to figure out is why certain exceptions that were being overridden by Fault are now suddenly returning the WebOb error...

**Comment by bertjwregeer** [comment] 2016-03-29 21:33
I'm sorry, until there is more information available I will be closing this issue. If the problem still exists and you have a way to reproduce it, please feel free to reply or open a new issue.

Thank you!

**Closed by bertjwregeer** 2016-03-29 21:33 UTC
