### ISSUE TITLE
Semicolon followed by equals in Accept: header causes malformed request error

### ISSUE THREAD

**Issue by nate-johnston** [Pylons/webob#403] opened 2019-07-31 15:42 UTC
Starting in WebOb 1.8, we are seeing a regression in processing Accept headers that have a semicolon with an equals sign occurring later in the string.  This is coming from OpenStack Neutron, which uses WebOb to process these requests.  We have been able to pin it down to the WebOb 1.8 version; anything after that is broken, anything before that works.

A typical example Accept header that would see this issue is:

    Accept: application/json;charset=utf-8

What strings are involved is not deterministic of the issue.  Here are some permutations I tried:

- Accept: application/json;charset=utf-8 [406 Not Acceptable]
- Accept: application/json;charset [200 OK]
- Accept: application/json;hamburger [200 OK]
- Accept: application/json;hamburger=food [406 Not Acceptable]
- Accept: charset=UTF-8;application/json [200 OK]

See also: https://bugzilla.redhat.com/show_bug.cgi?id=1706222

**Comment by bertjwregeer** [comment] 2019-07-31 18:13
`application/json` doesn't have a charset, it is defined as a binary type that is UTF-8 by default unless there is a BOM provided. I would recommend not sending it in the first place, but if you can't fix the clients...

I need more information on where this regression exists or how you are using the WebOb accept parsing, because using WebOb 1.8.2:

```
>>> a = create_accept_header('application/json;charset=utf-8')
>>> a
<AcceptValidHeader ('application/json;charset=utf-8')>

>>> a = create_accept_header('charset=UTF-8;application/json')
>>> a
<AcceptInvalidHeader>

>>> a = create_accept_header('application/json;hamburger=food')
>>> a
<AcceptValidHeader ('application/json;hamburger=food')>
```

Second, you should likely be aware, that if you use the `;charset=utf-8` version of the Accept header, you'll have to explicitly match it because of the way the RFC requires specificity:

```
>>> a = create_accept_header('application/json;charset=utf-8')
>>> a.acceptable_offers(['application/json'])
[]
>>> a.acceptable_offers(['application/json;charset=utf-8'])
[('application/json;charset=utf-8', 1.0)]
```

Even using the old `best_match` algorithm that is the case:

````
>>> a.best_match(['application/json', 'application/json;charset=utf-8'])
'application/json;charset=utf-8'
>>> a.best_match(['application/json'])
None
>>>
```

**Comment by bertjwregeer** [comment] 2019-08-02 05:48
@nate-johnston unless I get more information I am unable to help and will close this issue. I believe this can likely be fixed in pecan or neutron directly, and the current parsing works correctly in WebOb (and matches the RFC).

**Comment by bertjwregeer** [comment] 2019-08-14 21:45
Closing this until more information comes available.

**Closed by bertjwregeer** 2019-08-14 21:45 UTC
Labels: needs-info

**Comment by radez** [comment] 2020-07-27 15:00
@bertjwregeer I've picked this issue back up to take a look at it and try and come to resolution where the right way to handle this is. Thanks for your previous information. It's aided in working towards the decision for what action to take.

One question left re: webob in this process:
passing the 'application/json;charset=utf-8' accept header would match application/json in webob 1.7. When we started to use webob 1.8 is when it no longer matched the less specific match. Would this be considered a regression in functionally from 1.7 to 1.8?

**Comment by bertjwregeer** [comment] 2020-07-27 16:31
This issue was so long ago I don't have the necessary context in front of me. Please provide test code that runs on WebOb 1.7 vs 1.8 that does not involve me attempting to go through the OpenStack source code to figure out what or how it attempts to do parsing of the accept header there.

At this time, I am also very unlikely to consider it a regression that requires follow-up or changes on the side of WebOb. The new accept parsing in WebOb is much more stringent and much more standards compliant. It's documented and the changes necessary to code to make it compliant with the newer version of WebOb are not difficult (and in fact improve the accept handling of the application to be more standards compliant).

**Comment by bertjwregeer** [comment] 2020-07-27 16:33
Also, please re-read the thread, `application/json` is considered a binary type and doesn't have a charset, clients sending a charset are doing it wrong, but if you want to continue accepting that data, you'll need to explicitly opt-in by passing both `application/json` and `application/json;charset=utf-8` to `acceptable_offers`

**Comment by mmerickel** [comment] 2020-07-27 16:46
> Accept: application/json;charset [200 OK]
> Accept: application/json;hamburger [200 OK]

These are invalid accept headers so webob converts them to `AcceptInvalidHeader` type. It's up to your app what to do with invalid headers but most apps will default to just match to json there and thus no one notices the invalid headers.

You might consider some middleware that sanitizes the invalid mimetype by stripping the `charset=utf-8` from it if present (charset is not a valid parameter on application/json).

The current algorithm rejects offers that are not as specific as what the client requested. I think it's worth considering a `strict=False` option to `acceptable_offers` which would match if the client contains parameters and the offer does not contain parameters.

**Comment by radez** [comment] 2020-07-27 18:54
Thanks for the info, We've been leaning towards sanitizing the incoming header. Maybe that strict=False could be the right fix. I'll do some more testing and be in touch. The fact that the new accept parsing is more compliant indicates we should fix this higher up the stack. Thanks!

**Comment by radez** [comment] 2020-07-29 20:59
We ended up fixing this in pecan.
https://github.com/pecan/pecan/pull/119

Though, If the strict=False is still of interest I don't mind putting a patch together and we could update pecan to consume that functionality.
