### ISSUE TITLE
WebOb-1.0.3 and AuthKit-0.4.5 incompatibility

### ISSUE THREAD

**Issue by blaflamme** [Pylons/webob#94] opened 2013-01-20 18:57 UTC
I moved this issue from @tjelle located here pylonshq to this project:

https://github.com/Pylons/pylonshq/issues/12

I have a pylons project that uses AuthKit in a similar fashion to that outlined in the pylons book:

http://pylonsbook.com/en/1.1/authentication-and-authorization.html#authkit

Everything was working fine until I upgraded from WebOb-1.0.1 to WebOb-1.0.3. When using WebOb-1.0.3 it becomes impossible to login. After entering the username and password the signin page appears to simply refresh, removing the username and password.

If this is not the right place to report this it would be great if you could let me know who I should get in contact with. I could not find any contact details on the WebOb website:

http://pythonpaste.org/webob/

**Comment by lennardk** [comment] 2015-06-26 17:39
I have the same issue, but with different versions:

Upgraded from debian wheezy to debian jessie: webob from 1.1.1 to 1.4

I've tracked the cause to BaseRequest.POST(), where in calling cgi.FieldStorage something seems to happen to cause paste.parsed_formvars to not see the POST variables any more.

I think the FakeCGIBody replacing wsgi.input might be somehow insufficient for paste.parsed_formvars somewhere down the line, but I find it hard to pinpoint exactly what is going wrong.

**Comment by mmerickel** [comment] 2015-06-26 17:50
AuthKit was last updated/released in 2009. Any incompatibilities here need to be fixed in AuthKit or by using an older version of webob. I don't think we can accommodate an issue like this as none of the core devs are likely to dive into AuthKit. It sounds to me like AuthKit is relying on undocumented portions of webob. On a side note I believe webob 1.4.1 removed the use of `FakeCGIBody`.

If there really is a bug in webob then please open a specific issue with a reproducible example.

**Closed by mmerickel** 2015-06-26 17:50 UTC
